server {
    listen 80;
    server_name dev.app.social.aleherse.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    server_name dev.app.social.aleherse.com;

    ssl_certificate /certs/cert.pem;
    ssl_certificate_key /certs/cert-key.pem;

    root /app/apps/web/dist;
    index index.html;

    location / {
        try_files $uri /index.html;
    }
}
